import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildDeferredLightingWgsl } from "../../../webg/DeferredLightingPass.js";
import { buildWaterSurfaceWgsl } from "../../../webg/WaterSurfaceWgsl.js";
import { buildComputeParticleRenderWgsl } from "../../../webg/ComputeParticleShaders.js";
import { buildPbrForwardHdrWgsl } from "../../../webg/PbrForwardShader.js";
import SmoothShader from "../../../webg/SmoothShader.js";

assert.doesNotMatch(buildDeferredLightingWgsl(), /causticField|binding\(17\)/);
assert.match(buildDeferredLightingWgsl(128, { caustics: true }), /waterDiffuse - ordinaryDiffuse/);
assert.match(buildDeferredLightingWgsl(128, { caustics: true }), /sample.a - local.y/);
const source = buildWaterSurfaceWgsl();
assert.match(source, /specularEnvironment/);
assert.match(source, /camera.lightColor/);
assert.doesNotMatch(source, /reflectedSky/);
assert.match(source, /textureStore\(depthOutput/);
assert.match(source, /textureStore\(normalOutput/);
assert.doesNotMatch(buildComputeParticleRenderWgsl(), /waterDepth/);
assert.match(buildComputeParticleRenderWgsl({ behindWater: true }), /waterDepth/);
const smooth = new SmoothShader({});
assert.doesNotMatch(buildPbrForwardHdrWgsl(smooth.wgslSrc), /waterDepth/);
assert.match(buildPbrForwardHdrWgsl(smooth.wgslSrc, 128, { waterDepthClip: true }), /fragPosition.z >= waterFront/);
const pipeline = readFileSync(new URL("../../../webg/ComputeEffectPipeline.js", import.meta.url), "utf8");
assert.ok(pipeline.indexOf("system.layers.encode") < pipeline.indexOf("system.composite"));
assert.ok(pipeline.indexOf("system.composite") < pipeline.indexOf("this.transparencyPass.encode"));
assert.ok(pipeline.indexOf("system.composite") < pipeline.indexOf("this.fogPass.encode"));
assert.ok(pipeline.indexOf("system.composite") < pipeline.indexOf("this.dofPass.encode"));
assert.ok(pipeline.indexOf("system.composite") < pipeline.indexOf("this.bloomPass.encode"));
console.log("water variant and pipeline contracts passed");
